### ISSUE TITLE
Include category and subcategory id in item response

### ISSUE THREAD

**Issue by c-trimm** [OpenAlbion/api#1]
I'd like to be able to query the data to, say, get all head armor. Currently, there isn't a simple way to do so. My first inclination was to simply fetch the armor categories and the IDs for each of the head gear types, then fetch all of the armors and filter it by those IDs. But since those IDs aren't include on the item data, there's no way to do that, either. Instead, I'd have to make at least 4 requests (armorCategories, armor subcat = cloth head, armor subcat = leather head, armor subcat = plate head) each time I wanted to get that data. When you're only allowing 60 reqs/sec, it could add up quickly if I get a lot of users.

All that said, thanks a ton for providing this API, it's extremely helpful!

**Comment by PyaeSoneAungRgn** [comment]
Thanks for using our api. 
We added category and subcategory data at weapon, armor, accessory and consumable V3 endpoints.
Sorry for late reply
